---
name: diag-env-test

on:
  push:
    branches: [tfapplyfix]

jobs:
  first:
    uses: ./.github/workflows/_diag-reusable.yml
    with:
      stack: first
      mode: apply
      environment: aws-prod

  second:
    needs: first
    uses: ./.github/workflows/_diag-reusable.yml
    with:
      stack: second
      mode: apply
      environment: aws-prod
